### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/WebApp#47]
It seems like every service needs to connect to a database. I'm not familiar with SQL and don't know how to set up these databases correctly. Would you please add more detailed steps in the README file?

**Comment by Anduin2017** [comment]
Good Issue. Ok.

Of course, the project can be run locally. But for the document part, we are still working on it.

I will add more details. But you as know this project is a big platform based on micro-services theory. So running it locally is different from running an app on it. So there are so many for us to talk about.

This issue will remain opening until the document is finished.
